language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_success:
  - 'npm run coverage:send'
